# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a587a1efe2bc9f01a7e1840e1a57403e86a588166ecf201fce2b74de9e1dd7c337443a00fa10c3f29b1605f616c255aad8ae15c31d5373f2e9e122b83c4b4f1a

test:
  secret_key_base: e193cc07d2348439b1cad1a0f045946619a0db69ead1706828c0fce0baca74ee7ebb054127fd8ff3a98e9241a1515b0fb0d1a0c3ea3c56472069ea5b48320396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
